<?php
/*******************************************************************************
    user_agent.inc: an array containing browser HTTP_USER_AGENT values for testing
    Copyright (C) 2001 Roger Raymond ~ epsilon7@users.sourceforge.net

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*******************************************************************************/
$user_agent = array(
'mozilla/5.0 (macintosh; u; darwin power macintosh; rv:0.9.9+) gecko/20020223',
'Mozilla/3.0 (compatible; Opera/3.0; Windows 95/NT4)',
'Mozilla/4.0 (compatible; MSIE 5.0; Windows 2000) Opera 5.11  [en]',
'Mozilla/4.0 (compatible; MSIE 4.01; Windows 98)',
'Mozilla/4.0 (compatible; MSIE 6.0b; Windows NT 5.0)',
'Mozilla/4.5 [en] (Win95; U)',
'Mozilla/4.5 (Macintosh; U; PPC)',
'Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:0.9+) Gecko/20010509',
'Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; m18) Gecko/20010131 Netscape6/6.01',
'Opera/5.11 (Windows 2000; U)  [en]',
'NCSA Mosaic/2.6b1 (X11;UNIX_SV 4.2MP R4000) libwww/2.12 modified',
'Lynx/2.7 libwww-FM/2.14',
'amaya/V4.3.2 libwww/5.3.1',
'Mozilla/4.0 (compatible; MSIE 5.5; Mac_PowerPC; OmniWeb/4.0)',
'mozilla/4.0 (compatible; msie 5.0; linux 2.4.16 i686) opera 5.0  [en]',
'mozilla/5.0 (compatible; konqueror/2.2.1; linux)',
'mozilla/4.0 (compatible; msie 6.0; windows nt 5.1; q312461)',
'mozilla/4.0 (compatible; msie 5.5; windows 98; win 9x 4.90)',
'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-US; rv:1.0.0) Gecko/20020529'
);
?>