/* author: Elpidio Latorilla */
/* Generated by AceHTML Freeware http://freeware.acehtml.com */
/* Creation date: 17.08.2002 */
function chkForm(obj)
{
	var new_value=0;
	for (i=0; i<obj.new_main_item.length; i++)
	{
	   if(obj.new_main_item[i].checked)
	   {
	    new_value=obj.new_main_item[i].value;
		 break;
	  }
	}
	if(obj.old_main_item.value==new_value)
	{
		 return false;
	}
}
