/* author: Lorilla Bong */
/* Generated by AceHTML Freeware http://freeware.acehtml.com */
/* Creation date: 21.12.2001 */
// this js file needs the setdatetime.js file 
function isvalidtime(d, lang) {
	val = d.value;
	if (isNaN(val)) {
		xval3 = "";
		for (i = 0; i < val.length; i++) {
			xval2 = val.slice(i, i + 1);
			// if (!isNaN(xval3 + xval2)) {xval3=xval3 + xval2;}
			if (isNaN(xval2)) {
				d.value = xval2;
				setTime(d, lang);
				return;
			}
		}
		d.value = xval3;

	} else {
		v3 = val;
		if ((v3 == 24) && (v3.length == 2))
			v3 = "00";
		if (v3 > 24) {

			switch (v3.length) {

			case 2:
				v1 = v3.slice(0, 1);
				v2 = v3.slice(1, 2);
				if (v2 < 6)
					v3 = "0" + v1 + "." + v2;
				else
					v3 = v3.slice(0, 1);
				break;
			case 3:
				v1 = val.slice(0, 2);
				v2 = val.slice(2, 3);

				if (v2 < 6)
					v3 = v1 + "." + v2;
				else
					v3 = v3.slice(0, 2);
				break;
			case 4:
				v3 = val.slice(0, 3);
				break;
			}

		}
		switch (v3.length) {

		case 2:
			v1 = v3.slice(0, 1);
			v2 = v3.slice(1, 2);
			if (v2 == ".")
				v3 = "0" + v3;
			break;

		case 3:
			v1 = v3.slice(0, 2);
			v2 = v3.slice(2, 3);
			if (v2 != ".")
				if (v2 < 6)
					v3 = v1 + "." + v2;
				else
					v3 = v1;
			break;
		case 4:
			if (v3.slice(3, 4) > 5)
				v3 = v3.slice(0, 3);
			break;
		}
		if (v3.length > 5)
			v3 = v3.slice(0, v3.length - 1);
		d.value = v3;
	}

}
