/* author: Lorilla Bong */
/* Generated by AceHTML Freeware http://freeware.acehtml.com */
/* Creation date: 29.03.2002 */

function ssm(menuId) {
	if (brwsVer >= 4) {
		if ((curSubMenu != '') && (menuId != curSubMenu))
			hsm();
		if (menuId != curSubMenu) {
			if (document.all) {
				eval('document.all.' + menuId).style.visibility = 'visible';
			} else {
				eval('document.' + menuId).visibility = 'show';
			}
			curSubMenu = menuId;
		} else if (curSubMenu != '')
			hsm();
	}
}
function hsm() {
	if (curSubMenu == "")
		return;
	else if (brwsVer >= 4) {
		if (document.all) {
			eval('document.all.' + curSubMenu).style.visibility = 'hidden';
		} else {
			eval('document.' + curSubMenu).visibility = 'hide';
		}
		curSubMenu = '';
	}
}
var brwsVer = parseInt(navigator.appVersion);
var timer;
var curSubMenu = '';
