/* author: Lorilla Bong */
/* Generated by AceHTML Freeware http://freeware.acehtml.com */
/* Creation date: 17.06.01 */
function syncDept(d,s)
{
	//var s=document.chgdept.saal;
	//alert(d.value);
	switch(d.value)
	{
		case "plop": s.options[0].selected=true;break;
		case "hnop": s.options[10].selected=true;break;
		case "gyn_op": s.options[3].selected=true;break;
		case "allg_op": s.options[2].selected=true;break;
		case "unfall_op": s.options[8].selected=true;break;
		case "augen_op": s.options[16].selected=true;break;
		default: s.options[0].selected=true;
	}
	
}

function syncSaal(d,s)
{
	var v=d.value;
	//var s=document.chgdept.dept;
	if((v=="a")||(v=="b")||(v=="11")||(v=="12")) s.options[0].selected=true;
	if((v=="9")||(v=="10")) s.options[1].selected=true;
	if((v=="1")||(v=="4")||(v=="5")||(v=="6")) s.options[2].selected=true;
	if((v=="7")||(v=="8")) s.options[3].selected=true;
	if((v=="2")||(v=="3")||(v=="13")||(v=="14")) s.options[4].selected=true;
	if(v=="15") s.options[5].selected=true;

}
