<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
require_once('./roots.php');
require_once($root_path.'include/inc_environment_global.php');
?>
<?php html_rtl($lang); ?>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf8">
<title>Ringraziamenti</title>
</head>
<body onLoad="if(window.focus) window.focus()">
<font face="verdana,arial" size=6 color="#0000ff">Ringraziamenti</fonts>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15
             src="../../gui/img/common/default/pixel.gif"
             width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../fotos/credits/claudio_torbinio.jpg" border=0  align=right vspace=10>
			<b>Claudio Giulio Torbinio (IT)</b>
			<p>
			Translation of Care2x to Italian<br>
			
			<p>Claudio is an IT analyst with Bachelor degree, and a nurse with Phd degree.
			He is 41 years old and has worked over care2x since 2004.
			He has improved the Italian translation of Care2x.
			Claudio is creating a module for the Nursing process (like a DRG).
			He works together with an Italian commitee for Italian translation of ICD10 and OPS-301.
			<P><a href="mailto:claudiogiulio@email.it"><u>Si puo' contattare Claudio Giulio Torbinio qui.</u></a>
</TD></TR></TBODY></TABLE>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15
            src="../../gui/img/common/default/pixel.gif"
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P><img src="../../fotos/credits/gabriele_cicala.jpg"  border=0  align=right vspace=10>
			<b>La traduzione italiana di sito web (www.care2x.com) � sviluppata e gestita da Gabriele Cicala.</b>
			<p>
			Gabriele Cicala � nato a Rossano in provincia di Cosenza nel 1970.
  Ha conseguito la laurea in ingegneria delle telecomunicazioni al Politecnico di Torino.
  Attualmente lavora in una societ� informatica in qualit� di consulente. <p>Fin dal primo momento in cui ha conosciuto l'ambiente Linux 
e open-source ha sempre avuto interesse per ogni tipo di progetto. Nonostante non appartenga propriamente all'ambiente medico ha deciso di
unirsi al progetto in quanto crede nelle stesse cose in cui credono il
suo ideatore e tutti i suoi collaboratori.
			<P><a href="mailto:gabcicala@tiscali.it"><u>Si pu� contattare Gabriele Cicala qui.</u></a>
</TD></TR></TBODY></TABLE>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../fotos/credits/giuseppe_scarpi.jpg"  width=135 height=170 border=0  align=right vspace=10>
			<b>La versione italiana di CARE 2X � stata fatta da Giuseppe Scarpi:</b>
			<p>
			Giuseppe Scarpi � nato a Roma nel 1967.<p>
E' laureato in ingegneria elettronica ed ha lavorato per molte aziende nel settore biomedico, dove ha compreso 
le profonde relazioni tra il mondo biomedico e quello informatico.
Utilizza ed apprezza sia Linux che Windows in quanto "<i>entrambi sono il risultato di un immenso lavoro umano, 
ed entrambi meritano rispetto</i>".<p>
Ha deciso di unirsi attivamente alla causa dell'Open Source in quanto 
"<i>...questo � un mondo ideale che sopravviver� fintanto che sar� perfettamente in equilibrio: se si prende, bisogna anche dare in proporzione</i>".

			<P><a href="mailto:kalbun@inwind.it"><u>Si pu� contattare Giuseppe Scarpi qui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P>
			<b>
			Massimiliano Cuccia (IT)
			</b><p>
			Ha collaborato a sviluppare i moduli di visualizzazione DICOM.
			
			<P><a href="mailto:mcuccia@users.sourceforge.net"><u>Si pu� contattare Massimiliano Cuccia qui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P>
			<b>
			Daniele Ali (IT)
			</b><p>
			Ha collaborato a sviluppare i moduli di visualizzazione DICOM.
			
			<P><a href="mailto:alidan@users.sourceforge.net"><u>Si pu� contattare Daniele Ali qui.</u></a>
</TD></TR></TBODY></TABLE>

<!-- <hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P><img src="../../fotos/credits/daniel_zilli.jpg"  border=0  align=right vspace=10>
			<b>
			La traduzione braziliana-portugesa di CARE 2X e sito web (www.care2x.com) � stata fatta da Daniel Zilli.
			</b>
			
			<P><a href="mailto:danielz@cco.matrix.com.br"><u>Si pu� contattare Daniel Zilli qui.</u></a>
</TD></TR></TBODY></TABLE>
 -->

<hr>
<font face="verdana,arial" size=3 color="#0000ff">Altri ringraziamenti</font>
<font face="verdana,arial" size=1 > (in ordine alfabetico)</font>

<table border=0 cellspacing=1 cellpadding=1>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Agus M. Ramdan (ID)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Revisione del codice, care2x.com CMS</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Daniele Frijia (DE)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Controllo del livello di sicurezza, consulente php</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Luki Rustianto (ID)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Miglioramenti del livello di sicurezza</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Mat�j Hausenblas (FR)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Traduzione in  francese</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Muhammad Panji (ID)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Traduzione in indonesiano</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Nino Novak (DE)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Traduzione in tedesco di www.care2x.com</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Patxi Gomar�z (ES)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Traduzione in spagnolo</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Pawel Cyrta (PL)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Traduzione in polacco</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Prantar Deka (IN)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Modulo di fatturazione generale</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Roberto Nanucci (IT)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Mirror site care2x.it</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Simone Aveotti (IT)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Traduzione in italiano</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Thomas Wiedmann (DE)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Test, debugging e validazione degli script</font></td>
  </tr>
</table>

<font face="verdana,arial" size=1>Nota: questa � solo una lista parziale. Presto ci saranno ulteriori ringraziamenti.</font>
</body>
</html>
