<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
require_once('./roots.php');
require_once($root_path.'include/core/inc_environment_global.php');
?>

<?php html_rtl($lang); ?>

<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->

<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-2">
<title>Credits</title>

</head>

<body onLoad="if(window.focus) window.focus()">

<font face="verdana,arial" size=6 color="#0000ff">Credits</fonts>
<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>

        <TBODY>

        <TR>

          <TD><IMG height=15 

            src="../../gui/img/common/default/pixel.gif" 

            width=5 border=0></TD></TR>

        <TR>

          <TD vAlign=top><font face="verdana,arial" size=2>

            <P><img src="../../gui/img/common/default/pixel.gif"  width=135  border=0  align=right vspace=10>

			<b>Petr Roupec (CZ) translated CARE 2X to Czech.</b>
			<P><a href="mailto:roupec@sourceforge.net"><u>Petr Roupec can be contacted here.</u></a>

</TD></TR></TBODY></TABLE>
<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>

        <TBODY>

        <TR>

          <TD><IMG height=15 

            src="../../gui/img/common/default/pixel.gif" 

            width=5 border=0></TD></TR>

        <TR>

          <TD vAlign=top><font face="verdana,arial" size=2>

			<P><img src="../../fotos/credits/elpidio_latorilla_3.jpg" border=0  align=right vspace=10>

			<b>The first beta version of CARE 2X was created by Elpidio Latorilla:</b>

			<p>

			Professions: <br>Programmer, Surgery Nurse, Electronics & telecommunications technician

			<p>

			Areas of interest: <br>C, C++, PHP, Javascript, SQL, TCL/TK, HTML, Perl, ASP, Java

			<P><a href="mailto:elpidio@latorilla.com"><u>Elpidio Latorilla can be contacted here.</u></a>

</TD></TR></TBODY></TABLE>

<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>

        <TBODY>

        <TR>

          <TD><IMG height=15 

            src="../../gui/img/common/default/pixel.gif" 

            width=5 border=0></TD></TR>

        <TR>

          <TD vAlign=top><font face="verdana,arial" size=2>

			<P><img src="../../fotos/credits/giuseppe_scarpi.jpg"  border=0  width=135 height=170 align=right vspace=10>

			<b>Giuseppe Scarpi (IT) translated CARE 2X to italian.</b>

			<p>

			Giuseppe Scarpi was born in Rome, Italy, 35 years ago. 

			<p>He has a degree in Electronic Engineering and has worked for several companies in the biomedical sector, 

			where he developed an understanding about the relationships between medical and informatics worlds.<br>

He uses and appreciates both Linux and Windows, "<i>as both are the result of a great human work that must be respected</i>".<p>

He decided to actively join open source because: <br><i>"Such an ideal world can survive only if perfectly balanced. If you take something,

 you should also give back in proportion."</i>



			<P><a href="mailto:kalbun@inwind.it"><u>Giuseppe Scarpi can be contacted here.</u></a>

</TD></TR></TBODY></TABLE>



<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>

        <TBODY>

        <TR>

          <TD><IMG height=15 

            src="../../gui/img/common/default/pixel.gif" 

            width=5 border=0></TD></TR>

        <TR>

          <TD vAlign=top><font face="verdana,arial" size=2>

            <P><img src="../../fotos/credits/gabriele_cicala.jpg"  border=0  align=right vspace=10>

			<b>Gabriele Cicala (IT) translated most of the the www.care2x.com website to italian.</b>

			

			<P><a href="mailto:gabcicala@tiscali.it"><u>Gabriele Cicala can be contacted here.</u></a>

</TD></TR></TBODY></TABLE>



<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>

        <TBODY>

        <TR>

          <TD><IMG height=15 

            src="../../gui/img/common/default/pixel.gif" 

            width=5 border=0></TD></TR>

        <TR>

          <TD vAlign=top><font face="verdana,arial" size=2>

            <P><img src="../../fotos/credits/daniel_zilli.jpg"  border=0  align=right vspace=10>

			<b>Daniel Zilli (BR) translated CARE 2X and www.care2x.com website to  brazilian-portuguese.</b>

			

			<P><a href="mailto:danielz@cco.matrix.com.br"><u>Daniel Zilli can be contacted here.</u></a>

</TD></TR></TBODY></TABLE>



<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>

        <TBODY>

        <TR>

          <TD><IMG height=15 

            src="../../gui/img/common/default/pixel.gif" 

            width=5 border=0></TD></TR>

        <TR>

          <TD vAlign=top><font face="verdana,arial" size=2>

            <P><img src="../../fotos/credits/agus_mr.jpg"  border=0  align=right vspace=10>

			<b>Agus Muhammad Ramdan (ID) translated CARE 2X and www.care2x.com website to indonesian.</b>

			

			<P><a href="mailto:agusmr@mweb.co.id"><u>Agus M. Ramdan can be contacted here.</u></a>

</TD></TR></TBODY></TABLE>

<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>

        <TBODY>

        <TR>

          <TD><IMG height=15 

            src="../../gui/img/common/default/pixel.gif" 

            width=5 border=0></TD></TR>

        <TR>

          <TD vAlign=top><font face="verdana,arial" size=2>

            <P><img src="../../fotos/credits/thomas_wiedmann.jpg"  border=0  align=right vspace=10>

			<b>Thomas Wiedmann (DE) contributed the ff:</b>

			<p><font size=1>

			Complete testing <br>

			Debugging<br>

			DB 'optimistic locking' concept<br>

			DB optimizations<br>

			Validation scripts for date and numbers<p>

			</font>

			Thomas Wiedmann is a long time software developer and works in Stuttgart, Germany. He has

			been working with Gupta Team Developer and IBM DB2 since 7 years and is an

			IBM Certified UDB DB2 Administrator, too. Read more about DB2 in his book

			"DB2" ISBN 3-932311-80-9. He is an author for TOOLBOX (www.toolbox-mag.de),

			a Geman developer magazine.

		



			<P><a href="mailto:tho123@users.sourceforge.net"><u>Thomas Wiedmann can be contacted here.</u></a>

</TD></TR></TBODY></TABLE>



<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>

        <TBODY>

        <TR>

          <TD><IMG height=15 

            src="../../gui/img/common/default/pixel.gif" 

            width=5 border=0></TD></TR>

        <TR>

          <TD vAlign=top><font face="verdana,arial" size=2>

			<b>Nino Novak (DE) edited the german edition of www.care2x.com.</b>

			<p>

			Nino Novak is a poor lonesome cowboy. He shoots faster than he thinks. Sometimes a bit fussy.

			Loves "real gurus" and sophisticated discussions with them. Wants to help in creating a better

			world. Some scientific and medical background (thus joined the care2x project).

		



			<P><a href="mailto:nino@kflog.org"><u>Nino Novak can be contacted here.</u></a>

</TD></TR></TBODY></TABLE>

<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>

        <TBODY>

        <TR>

          <TD><IMG height=15 

            src="../../gui/img/common/default/pixel.gif" 

            width=5 border=0></TD></TR>

        <TR>

          <TD vAlign=top><font face="verdana,arial" size=2>

			<b>Patxi Gomaríz (ES) did the spanish translations.</b>

			<p>

			Patxi Gomaríz was born in the spring of 1966 in Murcia, Spain. His life and work revolve mostly around photography

			being a specialist in photography for Ophtalmology (fundus camera). He is an internet enthusiast and also designs 

			websites.<p>

			"<i>I think the open source code is an effective weapon against the negative effects of economic globalization specially in 

			fundamental areas which are important to humanity like health. For that reason, I feel proud of my small

			contribution to this great project.</i>"



			<P><a href="mailto:pgomariz@ono.com"><u>Patxi Gomaríz can be contacted here.</u></a>

</TD></TR></TBODY></TABLE>

<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>

        <TBODY>

        <TR>

          <TD><IMG height=15 

            src="../../gui/img/common/default/pixel.gif" 

            width=5 border=0></TD></TR>

        <TR>

          <TD vAlign=top><font face="verdana,arial" size=2>

			<b>Daniele Frijia (DE) checked the security aspects of CARE 2X.</b>

			<br>

			A few of his many contributions:<p>

			<font size=1>

			Advice on security<br>

			Consultations on php matters<br>

			He is the "sentinel" of the project

		</font>

		    <p>

			Daniele Frijia (born 81), currently working for an ISP in Nuremberg, Germany, dedicates his php

			knowledge to improve the security of Care2x. The intention is to open a new "market" (medical)

			for the open source community.



			<P><a href="mailto:daniele@infra.de"><u>Daniele Frijia kann hier kontaktiert werden.</u></a>

</TD></TR></TBODY></TABLE>

<hr>

<font face="verdana,arial" size=3 color="#0000ff">More credits</font>

<font face="verdana,arial" size=1 > (in alphabetical order)</font>



<table border=0 cellspacing=1 cellpadding=1>

  <tr>

    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Agus M. Ramdan (ID)</font></nobr>&nbsp;</td>

    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Code revisions, care2x.com CMS</font></td>

  </tr>

  <tr>

    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Daniele Frijia (DE)</font></nobr>&nbsp;</td>

    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Security checks, php consultant</font></td>

  </tr>

  <tr>

    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Dilip Bharatee (IN)</font></nobr>&nbsp;</td>

    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;ecomscience.com, full time programmers</font></td>

  </tr>

  <tr>

    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Luki Rustianto (ID)</font></nobr>&nbsp;</td>

    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Security enhancements</font></td>

  </tr>

  <tr>

    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Matêj Hausenblas (FR)</font></nobr>&nbsp;</td>

    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;French translation</font></td>

  </tr>

  <tr>

    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Muhammad Panji (ID)</font></nobr>&nbsp;</td>

    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Additional indonesian translations</font></td>

  </tr>

  <tr>

    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Nino Novak (DE)</font></nobr>&nbsp;</td>

    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;German edition of www.care2x.com</font></td>

  </tr>

  <tr>

    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Patxi Gomaríz (ES)</font></nobr>&nbsp;</td>

    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Spanish translation</font></td>

  </tr>

  <tr>

    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Pawel Cyrta (PL)</font></nobr>&nbsp;</td>

    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Polish translation</font></td>

  </tr>

  <tr>

    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Prantar Deka (IN)</font></nobr>&nbsp;</td>

    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Generic billing module</font></td>

  </tr>

  <tr>

    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Roberto Nanucci (IT)</font></nobr>&nbsp;</td>

    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;care2x.it mirror site</font></td>

  </tr>

  <tr>

    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Simone Aveotti (IT)</font></nobr>&nbsp;</td>

    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Additional italian translations</font></td>

  </tr>

  <tr>

    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Thomas Wiedmann (DE)</font></nobr>&nbsp;</td>

    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Testing, debugging, validation scripts</font></td>

  </tr>

</table>



<font face="verdana,arial" size=1>Note: This is a partial list. Additional credits are coming.</font>



</body>

</html>

