<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
 // globalize POST, GET, & COOKIE  vars
require('./roots.php');
require_once($root_path.'include/inc_environment_global.php');
require_once($root_path.'include/inc_charset_fx.php') // load the charset functions
?>
<?php html_rtl($lang); ?>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 25.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>
</head>
<body alink="#0000ff" vlink="#0000ff" link="#0000ff">
<font face="Arial" color="#cc0000" size=3><b>Hilfe</b></font><p>
<font face="Verdana, Arial" size=2><b>
<a href="../main/help-info.php?lang=de" target="HELPINFOFRAME">Erste Schritte</a><br>
<!--<a href="../help/de/help_de_contents.php" target="HELPINFOFRAME">Inhalt</a><br>
 <a href="#">Verzeichnis</a><br>
<a href="#">Suchen</a><br>
<a href="#">Tipps & Tricks</a><br>
<a href="#">Anleitungen</a></b></font>
 -->
<p>
 <p>
 <b>
<font color=#ff0000><b>*</b></font><a href="http://care2x.org/wiki/index.php/UM_-_English" target="HELPINFOFRAME">Online Manual</a>
<p>
<font color=#ff0000><b>*</b></font><a href="http://care2x.org/wiki/index.php/Workflow_Charts" target="HELPINFOFRAME">Workflow charts</a>
</b>
<p>
 (<font size=1>Internetanschluss erforderlich</font><font color=#ff0000><b>*</b></font>)

</body>
</html>
