<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 25.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>
</head>
<body alink="#0000ff" vlink="#0000ff" link="#0000ff">
<font face="Arial" color="#cc0000" size=3><b>Ajuda</b></font><p>
<font face="Verdana, Arial" size=2><b>
<a href="../main/help-info.php" target="HELPINFOFRAME">Passos iniciais</a><br>
<!--<a href="../help/en/help_en_contents.php" target="HELPINFOFRAME">Conteúdo</a><br>
 <a href="#" target="HELPINFOFRAME">Índice</a><br>
<a href="#" target="HELPINFOFRAME">Pesquisa</a><br>
<a href="#" target="HELPINFOFRAME">Dicas e Truques</a><br>
<a href="#" target="HELPINFOFRAME">Introduções</a></b>
 --><p>
 <p>
 <b>
<font color=#ff0000><b>*</b></font><a href="http://care2x.org/wiki/index.php/UM_-_English" target="HELPINFOFRAME">Online Manual</a>
<p>
<font color=#ff0000><b>*</b></font><a href="http://care2x.org/wiki/index.php/Workflow_Charts" target="HELPINFOFRAME">Workflow charts</a>
</b>
<P>
 (<font size=1>needs Internet connection</font><font color=#ff0000><b>*</b></font>)

</font>

</body>
</html>
