<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
 // globalize POST, GET, & COOKIE  vars
require('./roots.php');
require_once($root_path.'include/inc_environment_global.php');
require_once($root_path.'include/inc_charset_fx.php') // load the charset functions
?>
<?php html_rtl($lang); ?>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 25.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-9">
<title>Yardım</title>
</head>
<body alink="#0000ff" vlink="#0000ff" link="#0000ff">
<font face="Arial" color="#cc0000" size=3><b>Yardım</b></font><p>
<font face="Verdana, Arial" size=2>
<a href="../main/help-info.php?lang=tr" target="HELPINFOFRAME">İlk adımlar</a><br></b>
<!--<a href="../help/tr/help_tr_contents.php" target="HELPINFOFRAME">İçindekiler</a><br>
 <a href="#" target="HELPINFOFRAME">Fihrist</a><br>
<a href="#" target="HELPINFOFRAME">Arama</a><br>
<a href="#" target="HELPINFOFRAME">İpuçları</a><br>
<a href="#" target="HELPINFOFRAME">Tanıtımlar</a></b>
 --><p>
 <p>
 <b>
<font color=#ff0000><b>*</b></font><a href="http://207.44.195.231/~care2x/docswiki/index.php?UM - English" target="HELPINFOFRAME">Online El Kitabı</a>
<p>
<font color=#ff0000><b>*</b></font><a href="http://207.44.195.231/~care2x/docswiki/index.php?Workflow%20Charts" target="HELPINFOFRAME">İş akış şemaları</a>
</b>
<P>
 (<font size=1>internet bağlantısı gerektirir</font><font color=#ff0000><b>*</b></font>)

</font>

</body>
</html>
