<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
require_once('./roots.php');
require_once($root_path.'include/core/inc_environment_global.php');
?>
<?php html_rtl($lang); ?>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf8">
<title>Cr�ditos</title>
</head>
<body onLoad="if(window.focus) window.focus()">
<font face="verdana,arial" size=6 color="#0000ff">Cr�ditos</fonts>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P><img src="../../gui/img/common/default/pixel.gif"  border=0  align=right vspace=10 width=135>
			<b>Alfredo Rodrigues (PT)</b>
			<p>
			A tradu��o para Portugu�s deste software est� a ser efectuada por Alfredo Rodrigues. 
			<p>
			Para qualquer quest�o
			sobre a tradu��o, por favor, contactar com ele directamente em <a href="mailto:alf.rod@hotpop.com"><u>alf.rod(at)hotpop.com</u></a>
</TD></TR></TBODY>
</TABLE>
<hr>
<table cellSpacing=0 cellPadding=0 border=0 width=100%>
        <tbody>
        <tr>
          <td><img height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></td></tr>
        <tr>
          <td vAlign=top><font face="verdana,arial" size=2>
			<p><img src="../../fotos/credits/lopo_l_almeida.jpg"  
                                width=135 height=170 border=0  align=right vspace=10>
			<b>Lopo Lencastre de Almeida (PT)</b> is one of the most productive developers. 
			Some of his contributions to the project are:
                        <p><font size=1>
			Marketing, Promotion and Public Relations<br>
			Web and Logo design<br>
			Implementation &amp; maintenance of several web tools (Bugtracker, Forum, etc.)<br>
			Implementation &amp; maintenance of the new web site (almost done)<br>
			Forum moderation and administration<br>
			Code finder/digger<br>
			Consultations on PHP<br>
			Advises on security<br>
			Abstraction Layers Advisor (DB, Template, etc.)<br>
			Debugging<br>
			Ideas, discussions, hints, tips, etc.
			</font><p>
			Lopo L. de Almeida was born in Angola in 1966. He is working in the computer sector - ranging from commercial automation 
			to industrial automation - as a software developer and interface designer for more than 16 years now . During the last 5 years he 
			worked mostly  in web development and company management. He is the CEO/CTO of HumanEasy - a 
			partner of Care2002 project in charge of its <b>Public Relations and Marketing Management</b>.<br>
			He is also involved in many other GNU/GPL projects; some of them are in use at Care2x's site.<br>
			<p><a href="http://www.humaneasy.com" target="_blank"><u>Lopo L. de Almeida can be contacted here.</u></a>
</td></tr></tbody></table>
<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../fotos/credits/elpidio_latorilla_3.jpg" border=0  align=right vspace=10>
			<b>A primeira vers�o beta do CARE 2X foi criada por Elpidio Latorilla:</b>
			<p>
			Profiss�es: <br>Programador, Enfermeiro de Cir�rgia, T�cnico de Electr�nica e Telecomunica��es
			<p>
			�reas de interesse: <br>C, C++, PHP, Javascript, SQL, TCL/TK, HTML, Perl, ASP, Java
			<P><a href="mailto:elpidio@latorilla.com"><u>Elpidio Latorilla pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../fotos/credits/giuseppe_scarpi.jpg"  border=0  width=135 height=170 align=right vspace=10>
			<b>Giuseppe Scarpi (IT) traduziu o CARE 2X para Italiano.</b>
			<p>
			Giuseppe Scarpi nasceu em Roma, Italia e tem 35 anos. 
			<p>� graduado em Engenharia Electr�nica e tem trabalhado em v�rias empresas no sector biom�dico, 
			onde desenvolveu os seus conhecimentos sobre as rela��es entre o mundo m�dico e o mundo da inform�tica.<br>
Utiliza e aprecia tanto o Linux como o Windows, "<i>Ambos s�o o resultado de um grande trabalho humano e devem ser respeitados</i>".<p>
Decidiu aderir activamente ao C�digo Aberto porque: <br><i>"Um mundo ideal s� pode sobreviver se perfeitamente balanceado. Se se retira algo,
 deve-se tamb�m retribuir na mesma propor��o."</i>

			<P><a href="mailto:kalbun@inwind.it"><u>Giuseppe Scarpi pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P><img src="../../fotos/credits/gabriele_cicala.jpg"  border=0  align=right vspace=10>
			<b>Gabriele Cicala (IT) traduziu grande parte do site www.care2x.com para Italiano.</b>
			
			<P><a href="mailto:gabcicala@tiscali.it"><u>Gabriele Cicala pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P><img src="../../fotos/credits/daniel_zilli.jpg"  border=0  align=right vspace=10>
			<b>Daniel Zilli (BR) traduziu o CARE 2X e o site www.care2x.com para Portugu�s-Brasileiro.</b>
			<p>
			Daniel � um bom rapaz que quer viver uma vida feliz. Gosta de computadores, futebol e boa m�sica.
Tem 10 anos de exper�ncia em computadores e adora o que faz.
O Daniel tem uma empresa onde trabalha com produtos para ensino de inform�tica, software de c�digo aberto e tem a sua pr�pria distribui��o de linux.
			<P><a href="mailto:danielz@cco.matrix.com.br"><u>Daniel Zilli pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P><img src="../../fotos/credits/agus_mr.jpg"  border=0  align=right vspace=10>
			<b>Agus Muhammad Ramdan (ID) traduziu o CARE 2X e o site www.care2x.com para Indon�sio.</b>
			
			<P><a href="mailto:agusmr@mweb.co.id"><u>Agus M. Ramdan pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../fotos/credits/thomas_wiedmann.jpg"  border=0  width=135 align=right vspace=10>
			<b>Thomas Wiedmann (DE) contribuiu com:</b>
			<p><font size=1>
			Testes completos<br>
			Depura��o<br>
			Conceito da BD 'optimistic locking'<br>
			Optimiza��es da BD<br>
			Scripts de valida��o para datas e n�meros<p>
			</font>
			Thomas Wiedmann desenvolve software h� bastante tempo e trabalha em Estugarda, Alemanha. Ele tem
			trabalhado com a Gupta Team Developer, com IBM DB2 nos �ltimos 7 anos e � tamb�m
			IBM Certified UDB DB2 Administrator. Leia mais sobre DB2 no seu livro
			"DB2" ISBN 3-932311-80-9. � o autor de TOOLBOX (www.toolbox-mag.de),
			uma revista alem� sobre programa��o.
		

			<P><a href="mailto:tho123@users.sourceforge.net"><u>Thomas Wiedmann pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../gui/img/common/default/pixel.gif"  border=0  width=135 align=right vspace=10>
			<b>Nino Novak (DE) editou o site www.care2x.com em Alem�o.</b>
			<p>
			Nino Novak � um pobre e solit�rio cowboy. Dispara mais depressa do que pensa. As vezes � um pouco inquieto.
			Adora "real gurus" e ter discuss�es sofisticadas com eles. Quer ajudar a criar um mundo melhor.
			Tem alguns conhecimentos cient�ficos e m�dicos (pelo que se juntou ao projecto care2x).
		

			<P><a href="mailto:nino@kflog.org"><u>Nino Novak pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../gui/img/common/default/pixel.gif"  border=0  width=135 align=right vspace=10>
			<b>Patxi Gomar�z (ES) traduziu o CARE 2X para Espanhol.</b>
			<p>
			Patxi Gomar�z nasceu na primavera de 1966 em Murcia, Espanha. A sua vida e o seu trabalho centram-se principalmente na fotografia,
			� um especialista em fotografia para Oftalmologia (fundus camera). � um entusiasta da Internet e tamb�m desenvolve sites.<p>
			"<i>Eu penso que o C�digo Aberto � uma arma efectiva contra os efeitos negativos da economia globalizada especialmente em 
			�reas t�o fundamentais para a humanidade como a sa�de. Por esta raz�o, sinto muito orgulho na minha pequena contribui��o
			para este grande projecto.</i>"

			<P><a href="mailto:pgomariz@ono.com"><u>Patxi Gomar�z pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../gui/img/common/default/pixel.gif"  border=0  width=135 align=right vspace=10>
			<b>Daniele Frijia (DE) verificou o CARE 2X no que diz respeito a seguran�a.</b>
			<br>
			Algumas das suas contribui��es:<p>
			<font size=1>
			Conselhos sobre seguran�a<br>
			Consultoria sobre quest�es de PHP<br>
			Ele � o "sentinela" do projecto
		</font>
		    <p>
			Daniele Frijia (nascido em 81), trabalha actualmente para um ISP em Nuremberga, Alemanha, dedica os seus conhecimentos de PHP
			� melhoria, em termos de seguran�a, do Care2x. A inten��o � abrir as portas de um novo "mercado" (m�dico)
			� comunidade do C�digo Aberto.

			<P><a href="mailto:daniele@infra.de"><u>Daniele Frijia pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>
<hr>
<font face="verdana,arial" size=3 color="#0000ff">Mais Cr�ditos</font>
<font face="verdana,arial" size=1 > (por ordem alfab�tica)</font>

<table border=0 cellspacing=1 cellpadding=1>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Agus M. Ramdan (ID)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Revis�es ao c�digo, care2x.com CMS</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Daniele Frijia (DE)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Testes de seguran�a, Consultoria PHP</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Dilip Bharatee (IN)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;ecomscience.com, programadores a tempo inteiro</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Luki Rustianto (ID)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Melhorias de seguran�a</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Mat�j Hausenblas (FR)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Tradu��o para Franc�s</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Muhammad Panji (ID)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Tradu��es adicionais para Indon�sio</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Nino Novak (DE)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Edi��o Alem� do www.care2x.com</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Patxi Gomar�z (ES)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Tradu��o para Espanhol</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Pawel Cyrta (PL)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Tradu��o para Polaco</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Prantar Deka (IN)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;M�dulo gen�rico de factura��o</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Roberto Nanucci (IT)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;care2x.it espelho do site</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Simone Aveotti (IT)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Tradu��es adicionais para Italiano</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Thomas Wiedmann (DE)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Testes, depura��o e valida��es de scripts</font></td>
  </tr>
</table>

<font face="verdana,arial" size=1>Nota: Esta � uma lista parcial. Mais Cr�ditos ir�o ser adicionados.</font>

</body>
</html>
