<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 25.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>
</head>
<body alink="#0000ff" vlink="#0000ff" link="#0000ff">
<font face="Arial" color="#cc0000" size=3><b>Aiuto</b></font><p>
<font face="Verdana, Arial" size=2><b>
<a href="../main/help-info.php" target="HELPINFOFRAME">Primi passi</a><br>
<!--<a href="#">Sommario</a><br>
<a href="#">Indice analitico</a><br>
<a href="#">Ricerca</a><br>
<a href="#">Suggerimenti</a><br>
<a href="#">Presentazioni</a></b></font>-->
 <p>
 <b>
<font color=#ff0000><b>*</b></font><a href="http://care2x.org/wiki/index.php/UM_-_English" target="HELPINFOFRAME">Manuali in linea (inglese)</a>
<p>
<font color=#ff0000><b>*</b></font><a href="http://care2x.org/wiki/index.php/Workflow_Charts" target="HELPINFOFRAME">Diagrammi dei flusso di lavoro</a>
</b>
<P>
 (<font size=1>Richiede connessione ad Internet</font><font color=#ff0000><b>*</b></font>)

</font>
</body>
</html>
