<?php 
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
require('./roots.php');
require($root_path.'include/core/inc_environment_global.php');
define('LANG_FILE','aufnahme.php');
$local_user='aufnahme_user';
require_once($root_path.'include/core/inc_front_chain_lang.php');
require_once($root_path.'include/core/inc_config_color.php');
require_once($root_path.'include/core/inc_date_format_functions.php');

//$thisfile=basename(__FILE__);


if(!isset($db) || !$db) include_once($root_path.'include/core/inc_db_makelink.php');


$sql="SELECT encounter_nr,date,type,notes FROM care_encounter_immunization WHERE nr=$nr";
if($result=$db->Execute($sql)){
	if($rows=$result->RecordCount()) $imm=$result->FetchRow();
}
?><?php html_rtl($lang); ?>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<head>

<title><?php echo $LDImmunization; ?></title>


</head>
<body onBlur="window.close()"><font face=arial>

 <font size=3 color="#000099"><b><?php echo $_SESSION['sess_full_en']; ?></b></font><br>
 <font size=2 color="#000099"><b><?php echo @formatDate2Local($imm['date'],$date_format); ?></b></font>


<table border=0 cellpadding=0 cellspacing=0 bgcolor="#efefef">
  <tr>
    <td>
	
	<table border=0 cellspacing=1>
	

   <tr>
     <td background="../../gui/img/common/default/tableHeaderbg.gif">
	 <font face=arial color="#efefef" size=3><b><?php echo $LDImmunization.' '.$LDNotes.' ('.$imm['type'].')';  ?> </b>
	 </td>
   </tr>

<?php
    //echo $mode;
    if ($rows) 
	{ 
?> 
   <tr bgcolor="#ffffff">
     <td ><font face=arial size=2>
	 <?php
	 	echo nl2br($imm['notes']);
	 ?>
	 &nbsp;
	 </td>
   </tr>
<?php	     
	}
?>		 </table>
 
	</td>
  </tr>
</table>
			

</font>
</body>
</html>
